use_frameworks!

platform :ios, '9.0'

target 'PlayerFrameworkPod_Example' do
  pod 'PlayerFrameworkPod', :path => '../'

  target 'PlayerFrameworkPod_Tests' do
    inherit! :search_paths

    
  end
end
